FROM rust:1.94.0-alpine3.23 as builder

WORKDIR /app
COPY ./ /app

RUN apk add --no-cache musl-dev git cmake make g++ binutils linux-headers zlib-dev
RUN cargo build --release --bin stat_server --package stat_server --locked
RUN strip /app/target/release/stat_server

FROM scratch as production

COPY --from=builder /app/config.toml /config.toml
COPY --from=builder /app/target/release/stat_server /stat_server

WORKDIR /
EXPOSE 8080 9394

CMD ["/stat_server", "--cloud"]
